dist: focal
sudo: false
git:
  depth: 1
cache:
  apt: true
language: node_js
node_js:
- '10'
install:
- npm install
- npm install rollup -g
- travis_wait 20 npm install --only=dev
script:
- npm run coveralls
deploy:
  provider: npm
  email: nic30@seznam.cz
  on:
    tags: true
    branch: master
  api_key:
    secure: Ad41N92Qw/Iyj9u+gkLvTXF79ETvxay7kY3ZRAKI/hmLUKvggaZhrbxgWdTuWqcUQKESZhZ/jPZYgiqIlcyUrwfLWOPqusurw5GqZaNB6VI3MrkK9otHWu6C0XkQAqYYyZ+EtDS9M8vMSCbq0AYMsDkPdqcHg3iSXoqeVigvyo5RJwkvxbNzXWgF6QZILqAElcay4XC/8xioqWrm6onesLc/8A2Dkz2H3zES3A0c9fhK895HOYmO787RNJNg1sREDBPSJohbOLk3B6nxMkR2FtaH4hPm3ooyRu6wEI5vJG71W+SYZ4tLSnDt1dmAXwRwtkZqMuQtJuO9JrpxZxzhSowzOI5uHjb0Mf+FascPIB3gjgq6T0bEH4uZjhg8lc1iWbbgahyqLmSQQ7ePPiB55P7kPCGGQQEFMMKFkfPeCtEHWz7jHPJ9L3zGqJ/A8d+mLPHPnxpSIE9bPr6slLysYXqL59V190HhxqHWrV9ZzvbuilugA+ND67u54gpYLLhxAIZk8MLNtSnRYIaUyQqqZKcbmQ0YDEw1SUfhqer/yfjhJfABgi+rrP65kU48qIUW+JdDlThr1XKxv90dXYEx2j84EllOhoTlvNb/LGfWHRQIcoSBWyRnOLuLz6BHKO6dIkaaKR6jtffzfI6MNWpLe5aj1+WsanwXDC3qu2iVu/A=
