dist: trusty
sudo: false
git:
  depth: 1
cache:
  apt: true
language: node_js
node_js:
- '7'
install:
- npm install
script:
- npm run coveralls
deploy:
  provider: npm
  email: nic30@seznam.cz
  on:
    tags: true
    branch: master
  api_key:
    secure: JdiKKAVTTdOk5o3P/NFVZuyJpHoJM9eO0r/cnaa3LDCChnrsdZ3uakjGmJcccvw+XHvK1tXAUkq6m/+M6WvnzGXd4wrOCoTfN17xKHIKuZS5H29OvdztzZU2tcfuogX948tStSg6RFgWQWiVSSl575WLY1pqYvwEtKlUG9X7RQ+hHrvhz/zvxPh26Hl6agkDv4tttS+jHBknbpBD9i3iM6DCVJ9nSoNGkhjTIEesCMllz4eVtOtoC13kdIsGRAl1f20EfqIRsvKYEW4E9xaGXx/s+XLq1J68r4Qtq3zM207EaJttFk0nQZ7RKgoduHhlh1xyexqOOppPnHnVkyqttm35gBE3q68lcmAnZdfvhKRXnpeUvr6r4YOdEG1vitJX1blt+4+Vd34RYxylelVisoDojw6nM50ytiaBnhlnXMOVW3X5c7URf61vSQJKx7hOq4/48pB1FFZ3phg/ts/J8J7sncUE1eTHDHR5JUrP3X0xStpkUxjsue9JUyyxT1MZ3XrnQ26gRqhIa1/tXUvWKWDcxdJvSv2pw3CEwUQMh+fSvBWbWu2BYt+RdayxKK8qs6DTEPNhXHmMCgJ4pXb88/yuCR9l9Qj1iNlPzI9N9XSYmH4s4qOkKJxhMArdSzjWaYAe+QNp+LfGP17xLE5RTDH49L+iXboxihhKXQQ+0Co=

