dist: trusty
sudo: false
git:
  depth: 1
cache:
  apt: true
language: node_js
node_js:
- '7'
install:
- npm install
script:
- npm run coveralls
deploy:
  provider: npm
  email: nic30@seznam.cz
  on:
    tags: true
    branch: master
  api_key:
    secure: k5a0VLddlHEh4S+R73lEHfL8kmxOKMWD8n2xjILSB6i5aLUaewVRglRvW+9amXVhPAGIunaAciS30qy4NdlgAwfNK5xHMsFDmnyb7p9gEN1v+lzi0tZnngZPC6v0vC2eSzHH+/+r3goDuoJB3Semrb8hqnn+LJl0qoQBTQYXxmoYB+/lvy4QIOctmJsqNEXoatSU28/sqCDqfqMBUIsJRgEUA50ZDkqjBvT4agYQxT6bpGDnoSgm6aIUunKORSeHLKp2aIRUduD0yhFTXgON/4mcxckhTo5dCxlYTHIsyWuqUTqA/CRiiyhi1kbMvLBTtuRxrSXrAOjXBzXcFI7g44Z1uc+pCR07FG0WSv/FB4WuyivN/qYq7unTI/vgzFz/92PsSzAG3oiEFyQ9BwH33VWSQA3HQX9i9Z0jSXoUFKbbvjoQCwrrtTnBkoLWdy9ZOVXE2p04NlOcNhjtug8I4jIEBN1ERBzR3GAMjWWuy5SWYS2B/L/C4olZCD5jNhrvrWTyQ1R9vVuSnFskqoGxp+8Tspuc20rr6vrsMCfE7NX/W5+GvWgsijNmAHGr9Y6ynuDihMHPBbWQw/GDo8FlLElMhgksniekDGZ2GGvKntMJfdHn/HNpjqPsZ13i+YQ7G5x1ZyVTrTxgr6R99ccE8mhwwgJcdCNJUWqlYAwOuo8=
  password:
    secure: FMQaqxrFHRGOSybC24N0U0FkNaQ0tnTAXq9H7/B97+9Q0oxkt40gnZ1dd6ED+VbjhDPAX4rep4o2CDl+c6yEdS5FjQq9BlAZZq7T4oxq7fc5qphbHXMrtUGJfDNu24F+c1WqkzYuY3X/sJojT20loHQn0rT8gZmmb/d/8eR9XtnZftWKteKkuABbJMIOv0i65gLTuqh05fuG3gYR071aWGHdraqUG/8BbAFANNofVEXw9RtW4y7urHXcxVTQGySQzpeF6kL7Qx8ycBj+WvciMtsvHwkyE/Ra4CY3+3ptkkZ0cMe2Tz0ZSSMBunpC7pfUVEj69wkIxErHaOwD2pXfZ/XBUsgmEn/QHk3VGyLUJ+N/rsykZLnLkj2IX9ShfYAqO24LxKlZwYbmYoSTLEYN0eqd411RyNY2JF5btwFQ7U5RfE92BD1UzfDn0nPmned+XSAfHD60aJaTMLP5GZVwGBHoXgdVtIn0O81EmJNvqIQBKfr30Q1z2wuQ7jLV44CqPe25+WiF3cyGTKsKKkrYEX1LbMdXFpK+fz5yXG8c5hDk1FhfQkUF8h8kq6YV0QDyVtt8dDVqMyvfgvlHWoN1DS6D2S0391IiqohmzL721qmB80fFQbYqCM6N2uRZdBzWfkeWB/SYgSwKM3sPAUlPF6FGv8DnIKeKFmt+j9CKKwU=
